# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "idyl" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"

  version "0.1.0-rc.1"
  sha256 arm:          "98994819f33ddb8da0282a629c9428ab97e306df1fa166466fe0f53055765621",
         intel:        "71cde90d130e2b8d10e18a85ff6bfe1e2db9b3b66059d92755154839122ab16f",
         arm64_linux:  "3407797c47437ac4360d79f349b85b22622c007e3b381231ee2d52b7bc06683b",
         x86_64_linux: "a9ef132e34fae248009b1fb08b9af8fbfe6fc4e66056fe0f8f3b05505776e519"

  url "https://github.com/idyl-labs/cli/releases/download/v#{version}/idyl_#{version}_#{os}_#{arch}.tar.gz",
      verified: "github.com/idyl-labs/cli/"
  name "Idyl"
  desc "CLI for the Idyl open compute network"
  homepage "https://idyl.network"

  binary "idyl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/idyl"]
    end
  end
end
