# This file was generated by GoReleaser. DO NOT EDIT.
cask "purlview" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "a98145f3bd54c8a71cdb49280551c952f26e32968526e812fde5b51544c3bd43"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1f47095b768ceda4a214fea1c546b0efeb1154345be33d5a2013b85acb046b3"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f4762b955af67cbf146b1b373818b9ba101ff2c9ea1158ec99c701a7b889b699"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2381e41961913cc9bd809e98e6ab149ed8b15bc3688b8c38b257135e549009fc"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_linux_amd64.tar.gz"
    end
  end

  name "purlview"
  desc "Share your running app and improve it together"
  homepage "https://github.com/idyl-labs/purlview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "purlview"
  manpage "man/purlview-completion.1"
  manpage "man/purlview-list.1"
  manpage "man/purlview-login.1"
  manpage "man/purlview-logout.1"
  manpage "man/purlview-share.1"
  manpage "man/purlview-whoami.1"
  manpage "man/purlview.1"
  bash_completion "completions/purlview.bash"
  fish_completion "completions/purlview.fish"
  zsh_completion "completions/_purlview"

  postflight do
    system_command "#{HOMEBREW_PREFIX}/bin/purlview", args: ["daemon", "resume"], must_succeed: false
  end

  uninstall_preflight do
    system_command "#{HOMEBREW_PREFIX}/bin/purlview", args: ["daemon", "stop", "--maintenance", "--timeout", "20s"], must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Upgrading or uninstalling Purlview stops its local daemon and ends any
    active shares. Start a share again afterwards.
  EOS
end
