# This file was generated by GoReleaser. DO NOT EDIT.
cask "purlview" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "c46a6ec4d75969ccb63ccf60ee52419226c528a0ca364ce7bd1634f31ff73b75"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f3f87b0d91110e70444d18b7f7447f9b9cc2569855f568b2329e7507338c793"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7cfffd832599346a92a2536e0393452cabc043ca84761e551283c2a5e43c60eb"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a4ef9d04fc1536586d2686226420b4f63fa6f3ef8fa463e9af25440b5780be0a"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_linux_amd64.tar.gz"
    end
  end

  name "purlview"
  desc "Share your running app and improve it together"
  homepage "https://purlview.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "purlview"
  manpage "man/purlview-completion-bash.1"
  manpage "man/purlview-completion-fish.1"
  manpage "man/purlview-completion-powershell.1"
  manpage "man/purlview-completion-zsh.1"
  manpage "man/purlview-completion.1"
  manpage "man/purlview-devices-signout.1"
  manpage "man/purlview-devices.1"
  manpage "man/purlview-link.1"
  manpage "man/purlview-list.1"
  manpage "man/purlview-login.1"
  manpage "man/purlview-logout.1"
  manpage "man/purlview-share.1"
  manpage "man/purlview-stop.1"
  manpage "man/purlview-whoami.1"
  manpage "man/purlview.1"
  bash_completion "completions/purlview.bash"
  fish_completion "completions/purlview.fish"
  zsh_completion "completions/_purlview"

  postflight do
    system_command "#{HOMEBREW_PREFIX}/bin/purlview", args: ["daemon", "resume"], must_succeed: false
  end

  uninstall_preflight do
    system_command "#{HOMEBREW_PREFIX}/bin/purlview", args: ["daemon", "stop", "--maintenance", "--timeout", "20s"], must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Upgrading or uninstalling Purlview stops its local daemon and ends any
    active shares. Start a share again afterwards.
  EOS
end
