# This file was generated by GoReleaser. DO NOT EDIT.
cask "purlview" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "aa97098adeddd414be9a0164409f24916bee8066ab9035f113d4eba5b8751161"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5903677a3c4822f5135c38552e5645121354e93ded7ea25e34f84d8f19c9a29"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "04df35aa465dcc11347f55bbdef9ebb2f033661075f7a14441a2e2019b436103"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee357046954d4d0e9b41ab77b830fd01837b344bbf9beef2b8fc6a5de7778203"
      url "https://github.com/idyl-labs/purlview-releases/releases/download/v#{version}/purlview_#{version}_linux_amd64.tar.gz"
    end
  end

  name "purlview"
  desc "Share your running app and improve it together"
  homepage "https://purlview.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "purlview"
  manpage "man/purlview-completion.1"
  manpage "man/purlview-list.1"
  manpage "man/purlview-login.1"
  manpage "man/purlview-logout.1"
  manpage "man/purlview-share.1"
  manpage "man/purlview-whoami.1"
  manpage "man/purlview.1"
  bash_completion "completions/purlview.bash"
  fish_completion "completions/purlview.fish"
  zsh_completion "completions/_purlview"

  postflight do
    system_command "#{HOMEBREW_PREFIX}/bin/purlview", args: ["daemon", "resume"], must_succeed: false
  end

  uninstall_preflight do
    system_command "#{HOMEBREW_PREFIX}/bin/purlview", args: ["daemon", "stop", "--maintenance", "--timeout", "20s"], must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Upgrading or uninstalling Purlview stops its local daemon and ends any
    active shares. Start a share again afterwards.
  EOS
end
