# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idyl < Formula
  desc "CLI for the Idyl distributed computing platform"
  homepage "https://idyl.network"
  version "0.1.0-rc.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idyl-labs/cli/releases/download/v0.1.0-rc.1/idyl_0.1.0-rc.1_darwin_amd64.tar.gz"
      sha256 "71cde90d130e2b8d10e18a85ff6bfe1e2db9b3b66059d92755154839122ab16f"

      define_method(:install) do
        bin.install "idyl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idyl-labs/cli/releases/download/v0.1.0-rc.1/idyl_0.1.0-rc.1_darwin_arm64.tar.gz"
      sha256 "98994819f33ddb8da0282a629c9428ab97e306df1fa166466fe0f53055765621"

      define_method(:install) do
        bin.install "idyl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idyl-labs/cli/releases/download/v0.1.0-rc.1/idyl_0.1.0-rc.1_linux_amd64.tar.gz"
      sha256 "a9ef132e34fae248009b1fb08b9af8fbfe6fc4e66056fe0f8f3b05505776e519"
      define_method(:install) do
        bin.install "idyl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idyl-labs/cli/releases/download/v0.1.0-rc.1/idyl_0.1.0-rc.1_linux_arm64.tar.gz"
      sha256 "3407797c47437ac4360d79f349b85b22622c007e3b381231ee2d52b7bc06683b"
      define_method(:install) do
        bin.install "idyl"
      end
    end
  end
end
